import { Laptop, Brain, Users, HeartPulse, GraduationCap } from "lucide-react";
import type { RoleId } from "./exam-engine";
export const roles: Record<RoleId, {
    name: string;
    shortName: string;
    eyebrow: string;
    description: string;
    color: string;
    icon: typeof Laptop;
    details: string[];
    topics: string[];
    period: string;
    special?: string;
}> = {
    ti: { name: "Técnico de Informática", shortName: "Informática", eyebrow: "Ensino médio / técnico", description: "Tecnologia, redes, suporte e segurança para o serviço público.", color: "#1e6b5c", icon: Laptop, details: ["40 questões", "100 pontos", "Mínimo: 50 pontos", "10 LP · 3 RLM · 2 realidade · 25 específicos"], period: "Vespertino", topics: ["LGPD, segurança da informação, privacidade, senhas e cópias de segurança", "Windows 10, Windows 11, Windows Server e Active Directory", "Redes, cabeamento, dispositivos, modelo OSI, TCP/IP e navegação segura", "Computação em nuvem: Google Workspace, Microsoft 365 e AWS", "Hardware, manutenção, impressoras e periféricos", "Software, Office, ferramentas livres, PowerShell/CMD e organização de arquivos", "Atendimento, registro e acompanhamento de chamados", "Lei Orgânica do Município: servidores municipais"] },
    psychology: { name: "Psicólogo", shortName: "Psicologia", eyebrow: "Ensino superior", description: "Ética, políticas públicas, psicopatologia e atuação em rede.", color: "#9b4d7b", icon: Brain, details: ["50 questões", "100 pontos", "Mínimo: 50 pontos", "10 LP · 5 RLM · 5 realidade · 30 específicos"], period: "Matutino", topics: ["Código de Ética, bioética, avaliação psicológica, SATEPSI e documentos técnicos", "SUS, SUAS, atenção primária, secundária e terciária", "Psicanálise, TCC, humanista-existencial, sistêmica e sócio-histórica", "Psicopatologia, CID-11, DSM-5-TR e manejo de crises", "Comportamento suicida, autolesão, álcool e outras drogas", "Envelhecimento, violência e rede de proteção", "Psicologia hospitalar, luto, terminalidade e reabilitação psicossocial", "Crise, desastre, saúde coletiva, sexualidade e direitos reprodutivos", "Lei Orgânica: saúde e servidores municipais"] },
    social: { name: "Assistente Social", shortName: "Serviço Social", eyebrow: "Ensino superior", description: "SUAS, direitos sociais, instrumentos profissionais e políticas públicas.", color: "#9b6a28", icon: Users, details: ["50 questões", "100 pontos", "Mínimo: 50 pontos", "10 LP · 5 RLM · 5 realidade · 30 específicos"], period: "Matutino", topics: ["Código de Ética, sigilo e fundamentos históricos e teórico-metodológicos", "SUAS, LOAS, seguridade social, NOB-SUAS e benefícios socioassistenciais", "Direitos da criança, adolescente, pessoa idosa e pessoa com deficiência", "Lei Maria da Penha, proteção social e enfrentamento das violências", "Estado, sociedade, movimentos sociais e desigualdades", "Racismo, sexismo, capacitismo, diversidade e ações afirmativas", "Planejamento social e gestão pública municipal", "Estudo social, relatório, laudo, parecer e trabalho intersetorial", "Lei Orgânica: assistência social, criança, adolescente e idoso"] },
    acs: { name: "Agente Comunitário de Saúde", shortName: "Agente de Saúde", eyebrow: "Ensino médio / técnico", description: "Atenção básica, território, vigilância e vínculo com a comunidade.", color: "#2876a6", icon: HeartPulse, details: ["40 questões", "100 pontos", "Mínimo: 50 pontos", "10 LP · 3 RLM · 2 realidade · 25 específicos"], period: "Vespertino", topics: ["Constituição Federal, Leis nº 8.080/1990, 8.142/1990 e 11.350/2006", "PNAB, Atenção Primária, Estratégia Saúde da Família e processo de trabalho", "Territorialização, adscrição, diagnóstico comunitário e planejamento local", "Epidemiologia, indicadores, vigilâncias e notificação compulsória", "PNI e ações de imunização na Atenção Primária", "Educação em saúde, mobilização social e ações intersetoriais", "Ciclos de vida, grupos prioritários e vulnerabilidades", "Visita domiciliar, cadastros, sistemas, acolhimento e humanização", "CRAS e articulação com a rede de assistência social"] },
    pedagogy: { name: "Professor Pedagogo", shortName: "Pedagogia", eyebrow: "Ensino superior", description: "Educação básica, BNCC, inclusão, alfabetização e prática pedagógica.", color: "#5a54a4", icon: GraduationCap, details: ["50 questões + redação", "100 pontos", "Mínimo: 50 pontos", "10 LP · 5 RLM · 5 realidade · 30 específicos"], period: "Matutino", special: "O edital também prevê prova de redação e prova de títulos para este grupo de cargos.", topics: ["Constituição, LDB, ECA, PNE e BNCC na Educação Infantil e no Ensino Fundamental", "Sociedade, cultura, educação, aprendizagem e desenvolvimento humano", "Currículo, organização escolar, planejamento e Projeto Político-Pedagógico", "Educação inclusiva, acessibilidade, equidade e Lei Brasileira de Inclusão", "Alfabetização, letramento, avaliação e acompanhamento pedagógico", "Formação docente, gestão de sala e mediação de conflitos", "Tecnologias educacionais e recursos didáticos", "Lei Orgânica: servidores, educação, cultura, desporto e lazer"] },
};
